export const FiveMintes = {
  0: {
    "00:05": { value: "", isSys: null },
    "00:10": { value: "", isSys: null },
    "00:15": { value: "", isSys: null },
    "00:20": { value: "", isSys: null },
    "00:25": { value: "", isSys: null },
    "00:30": { value: "", isSys: null },
    "00:35": { value: "", isSys: null },
    "00:40": { value: "", isSys: null },
    "00:45": { value: "", isSys: null },
    "00:50": { value: "", isSys: null },
    "00:55": { value: "", isSys: null },
  },
  1: {
    "01:00": { value: "", isSys: null },
    "01:05": { value: "", isSys: null },
    "01:10": { value: "", isSys: null },
    "01:15": { value: "", isSys: null },
    "01:20": { value: "", isSys: null },
    "01:25": { value: "", isSys: null },
    "01:30": { value: "", isSys: null },
    "01:35": { value: "", isSys: null },
    "01:40": { value: "", isSys: null },
    "01:45": { value: "", isSys: null },
    "01:50": { value: "", isSys: null },
    "01:55": { value: "", isSys: null },
  },
  2: {
    "02:00": { value: "", isSys: null },
    "02:05": { value: "", isSys: null },
    "02:10": { value: "", isSys: null },
    "02:15": { value: "", isSys: null },
    "02:20": { value: "", isSys: null },
    "02:25": { value: "", isSys: null },
    "02:30": { value: "", isSys: null },
    "02:35": { value: "", isSys: null },
    "02:40": { value: "", isSys: null },
    "02:45": { value: "", isSys: null },
    "02:50": { value: "", isSys: null },
    "02:55": { value: "", isSys: null },
  },
  3: {
    "03:00": { value: "", isSys: null },
    "03:05": { value: "", isSys: null },
    "03:10": { value: "", isSys: null },
    "03:15": { value: "", isSys: null },
    "03:20": { value: "", isSys: null },
    "03:25": { value: "", isSys: null },
    "03:30": { value: "", isSys: null },
    "03:35": { value: "", isSys: null },
    "03:40": { value: "", isSys: null },
    "03:45": { value: "", isSys: null },
    "03:50": { value: "", isSys: null },
    "03:55": { value: "", isSys: null },
  },
  4: {
    "04:00": { value: "", isSys: null },
    "04:05": { value: "", isSys: null },
    "04:10": { value: "", isSys: null },
    "04:15": { value: "", isSys: null },
    "04:20": { value: "", isSys: null },
    "04:25": { value: "", isSys: null },
    "04:30": { value: "", isSys: null },
    "04:35": { value: "", isSys: null },
    "04:40": { value: "", isSys: null },
    "04:45": { value: "", isSys: null },
    "04:50": { value: "", isSys: null },
    "04:55": { value: "", isSys: null },
  },
  5: {
    "05:00": { value: "", isSys: null },
    "05:05": { value: "", isSys: null },
    "05:10": { value: "", isSys: null },
    "05:15": { value: "", isSys: null },
    "05:20": { value: "", isSys: null },
    "05:25": { value: "", isSys: null },
    "05:30": { value: "", isSys: null },
    "05:35": { value: "", isSys: null },
    "05:40": { value: "", isSys: null },
    "05:45": { value: "", isSys: null },
    "05:50": { value: "", isSys: null },
    "05:55": { value: "", isSys: null },
  },
  6: {
    "06:00": { value: "", isSys: null },
    "06:05": { value: "", isSys: null },
    "06:10": { value: "", isSys: null },
    "06:15": { value: "", isSys: null },
    "06:20": { value: "", isSys: null },
    "06:25": { value: "", isSys: null },
    "06:30": { value: "", isSys: null },
    "06:35": { value: "", isSys: null },
    "06:40": { value: "", isSys: null },
    "06:45": { value: "", isSys: null },
    "06:50": { value: "", isSys: null },
    "06:55": { value: "", isSys: null },
  },
  7: {
    "07:00": { value: "", isSys: null },
    "07:05": { value: "", isSys: null },
    "07:10": { value: "", isSys: null },
    "07:15": { value: "", isSys: null },
    "07:20": { value: "", isSys: null },
    "07:25": { value: "", isSys: null },
    "07:30": { value: "", isSys: null },
    "07:35": { value: "", isSys: null },
    "07:40": { value: "", isSys: null },
    "07:45": { value: "", isSys: null },
    "07:50": { value: "", isSys: null },
    "07:55": { value: "", isSys: null },
  },
  8: {
    "08:00": { value: "", isSys: null },
    "08:05": { value: "", isSys: null },
    "08:10": { value: "", isSys: null },
    "08:15": { value: "", isSys: null },
    "08:20": { value: "", isSys: null },
    "08:25": { value: "", isSys: null },
    "08:30": { value: "", isSys: null },
    "08:35": { value: "", isSys: null },
    "08:40": { value: "", isSys: null },
    "08:45": { value: "", isSys: null },
    "08:50": { value: "", isSys: null },
    "08:55": { value: "", isSys: null },
  },
  9: {
    "09:00": { value: "", isSys: null },
    "09:05": { value: "", isSys: null },
    "09:10": { value: "", isSys: null },
    "09:15": { value: "", isSys: null },
    "09:20": { value: "", isSys: null },
    "09:25": { value: "", isSys: null },
    "09:30": { value: "", isSys: null },
    "09:35": { value: "", isSys: null },
    "09:40": { value: "", isSys: null },
    "09:45": { value: "", isSys: null },
    "09:50": { value: "", isSys: null },
    "09:55": { value: "", isSys: null },
  },
  10: {
    "10:00": { value: "", isSys: null },
    "10:05": { value: "", isSys: null },
    "10:10": { value: "", isSys: null },
    "10:15": { value: "", isSys: null },
    "10:20": { value: "", isSys: null },
    "10:25": { value: "", isSys: null },
    "10:30": { value: "", isSys: null },
    "10:35": { value: "", isSys: null },
    "10:40": { value: "", isSys: null },
    "10:45": { value: "", isSys: null },
    "10:50": { value: "", isSys: null },
    "10:55": { value: "", isSys: null },
  },
  11: {
    "11:00": { value: "", isSys: null },
    "11:05": { value: "", isSys: null },
    "11:10": { value: "", isSys: null },
    "11:15": { value: "", isSys: null },
    "11:20": { value: "", isSys: null },
    "11:25": { value: "", isSys: null },
    "11:30": { value: "", isSys: null },
    "11:35": { value: "", isSys: null },
    "11:40": { value: "", isSys: null },
    "11:45": { value: "", isSys: null },
    "11:50": { value: "", isSys: null },
    "11:55": { value: "", isSys: null },
  },
  12: {
    "12:00": { value: "", isSys: null },
    "12:05": { value: "", isSys: null },
    "12:10": { value: "", isSys: null },
    "12:15": { value: "", isSys: null },
    "12:20": { value: "", isSys: null },
    "12:25": { value: "", isSys: null },
    "12:30": { value: "", isSys: null },
    "12:35": { value: "", isSys: null },
    "12:40": { value: "", isSys: null },
    "12:45": { value: "", isSys: null },
    "12:50": { value: "", isSys: null },
    "12:55": { value: "", isSys: null },
  },
  13: {
    "13:00": { value: "", isSys: null },
    "13:05": { value: "", isSys: null },
    "13:10": { value: "", isSys: null },
    "13:15": { value: "", isSys: null },
    "13:20": { value: "", isSys: null },
    "13:25": { value: "", isSys: null },
    "13:30": { value: "", isSys: null },
    "13:35": { value: "", isSys: null },
    "13:40": { value: "", isSys: null },
    "13:45": { value: "", isSys: null },
    "13:50": { value: "", isSys: null },
    "13:55": { value: "", isSys: null },
  },
  14: {
    "14:00": { value: "", isSys: null },
    "14:05": { value: "", isSys: null },
    "14:10": { value: "", isSys: null },
    "14:15": { value: "", isSys: null },
    "14:20": { value: "", isSys: null },
    "14:25": { value: "", isSys: null },
    "14:30": { value: "", isSys: null },
    "14:35": { value: "", isSys: null },
    "14:40": { value: "", isSys: null },
    "14:45": { value: "", isSys: null },
    "14:50": { value: "", isSys: null },
    "14:55": { value: "", isSys: null },
  },
  15: {
    "15:00": { value: "", isSys: null },
    "15:05": { value: "", isSys: null },
    "15:10": { value: "", isSys: null },
    "15:15": { value: "", isSys: null },
    "15:20": { value: "", isSys: null },
    "15:25": { value: "", isSys: null },
    "15:30": { value: "", isSys: null },
    "15:35": { value: "", isSys: null },
    "15:40": { value: "", isSys: null },
    "15:45": { value: "", isSys: null },
    "15:50": { value: "", isSys: null },
    "15:55": { value: "", isSys: null },
  },
  16: {
    "16:00": { value: "", isSys: null },
    "16:05": { value: "", isSys: null },
    "16:10": { value: "", isSys: null },
    "16:15": { value: "", isSys: null },
    "16:20": { value: "", isSys: null },
    "16:25": { value: "", isSys: null },
    "16:30": { value: "", isSys: null },
    "16:35": { value: "", isSys: null },
    "16:40": { value: "", isSys: null },
    "16:45": { value: "", isSys: null },
    "16:50": { value: "", isSys: null },
    "16:55": { value: "", isSys: null },
  },
  17: {
    "17:00": { value: "", isSys: null },
    "17:05": { value: "", isSys: null },
    "17:10": { value: "", isSys: null },
    "17:15": { value: "", isSys: null },
    "17:20": { value: "", isSys: null },
    "17:25": { value: "", isSys: null },
    "17:30": { value: "", isSys: null },
    "17:35": { value: "", isSys: null },
    "17:40": { value: "", isSys: null },
    "17:45": { value: "", isSys: null },
    "17:50": { value: "", isSys: null },
    "17:55": { value: "", isSys: null },
  },
  18: {
    "18:00": { value: "", isSys: null },
    "18:05": { value: "", isSys: null },
    "18:10": { value: "", isSys: null },
    "18:15": { value: "", isSys: null },
    "18:20": { value: "", isSys: null },
    "18:25": { value: "", isSys: null },
    "18:30": { value: "", isSys: null },
    "18:35": { value: "", isSys: null },
    "18:40": { value: "", isSys: null },
    "18:45": { value: "", isSys: null },
    "18:50": { value: "", isSys: null },
    "18:55": { value: "", isSys: null },
  },
  19: {
    "19:00": { value: "", isSys: null },
    "19:05": { value: "", isSys: null },
    "19:10": { value: "", isSys: null },
    "19:15": { value: "", isSys: null },
    "19:20": { value: "", isSys: null },
    "19:25": { value: "", isSys: null },
    "19:30": { value: "", isSys: null },
    "19:35": { value: "", isSys: null },
    "19:40": { value: "", isSys: null },
    "19:45": { value: "", isSys: null },
    "19:50": { value: "", isSys: null },
    "19:55": { value: "", isSys: null },
  },
  20: {
    "20:00": { value: "", isSys: null },
    "20:05": { value: "", isSys: null },
    "20:10": { value: "", isSys: null },
    "20:15": { value: "", isSys: null },
    "20:20": { value: "", isSys: null },
    "20:25": { value: "", isSys: null },
    "20:30": { value: "", isSys: null },
    "20:35": { value: "", isSys: null },
    "20:40": { value: "", isSys: null },
    "20:45": { value: "", isSys: null },
    "20:50": { value: "", isSys: null },
    "20:55": { value: "", isSys: null },
  },
  21: {
    "21:00": { value: "", isSys: null },
    "21:05": { value: "", isSys: null },
    "21:10": { value: "", isSys: null },
    "21:15": { value: "", isSys: null },
    "21:20": { value: "", isSys: null },
    "21:25": { value: "", isSys: null },
    "21:30": { value: "", isSys: null },
    "21:35": { value: "", isSys: null },
    "21:40": { value: "", isSys: null },
    "21:45": { value: "", isSys: null },
    "21:50": { value: "", isSys: null },
    "21:55": { value: "", isSys: null },
  },
  22: {
    "22:00": { value: "", isSys: null },
    "22:05": { value: "", isSys: null },
    "22:10": { value: "", isSys: null },
    "22:15": { value: "", isSys: null },
    "22:20": { value: "", isSys: null },
    "22:25": { value: "", isSys: null },
    "22:30": { value: "", isSys: null },
    "22:35": { value: "", isSys: null },
    "22:40": { value: "", isSys: null },
    "22:45": { value: "", isSys: null },
    "22:50": { value: "", isSys: null },
    "22:55": { value: "", isSys: null },
  },
  23: {
    "23:00": { value: "", isSys: null },
    "23:05": { value: "", isSys: null },
    "23:10": { value: "", isSys: null },
    "23:15": { value: "", isSys: null },
    "23:20": { value: "", isSys: null },
    "23:25": { value: "", isSys: null },
    "23:30": { value: "", isSys: null },
    "23:35": { value: "", isSys: null },
    "23:40": { value: "", isSys: null },
    "23:45": { value: "", isSys: null },
    "23:50": { value: "", isSys: null },
    "23:55": { value: "", isSys: null },
  },
  24: {
    "24:00": { value: "", isSys: null },
  },
};
