// label   名字   value id   parent父级id   path地址
export const NAV_MENU = [
  {
    label: "概况",
    value: "1",
    perms: [
      "overview:global:list",
      "overview:site:list",
      "overview:screen:list",
    ],
    children: [
      {
        label: "全局概况",
        parent: "1",
        value: "1-1",
        path: "/index/overview/all",
        perms: "overview:global:list",
        children: [],
      },
      {
        label: "站点概况",
        parent: "1",
        value: "1-2",
        path: "/index/overview/site",
        perms: "overview:site:list",
        children: [],
      },
      {
        label: "大屏展示",
        parent: "1",
        value: "1-3",
        path: "/screen",
        perms: "overview:screen:list",
        children: [],
      },
    ],
  },
  {
    label: "配电监控",
    value: "2",
    perms: [
      "monitor:overview:list",
      "monitor:monitoring:list",
      "monitor:condition:list",
      "monitor:alarm:list",
      "dynamic:control:list",
      "dynamic:analysis:list",
      "dynamic:video:list",
      "dynamic:monitoring:list",
      "dynamic:ring:list",
    ],
    children: [
      {
        label: "运行监控",
        parent: "2",
        value: "2-1",
        perms: [
          "monitor:overview:list",
          "monitor:monitoring:list",
          "monitor:condition:list",
          "monitor:alarm:list",
        ],
        children: [
          {
            label: "运行概况",
            parent: "2-1",
            value: "2-1-1",
            path: "/index/all/monitor/runoverview",
            perms: "monitor:overview:list",
            children: [],
          },
          {
            label: "实时监控",
            parent: "2-1",
            value: "2-1-2",
            path: "/index/all/monitor/monitoring",
            perms: "monitor:monitoring:list",
            children: [],
          },
          {
            label: "工况查询",
            parent: "2-1",
            value: "2-1-3",
            path: "/index/all/monitor/wcquery",
            perms: "monitor:condition:list",
            children: [],
          },
          {
            label: "告警列表",
            parent: "2-1",
            value: "2-1-4",
            path: "/index/all/monitor/alarm",
            perms: "monitor:alarm:list",
            children: [],
          },
        ],
      },
      {
        label: "电气火灾",
        parent: "2",
        value: "2-2",
        perms: [
          "dynamic:control:list",
          "dynamic:analysis:list",
          "dynamic:video:list",
          "dynamic:monitoring:list",
          "dynamic:realtime:list",
        ],
        children: [
          {
            label: "运行监测",
            parent: "2-2",
            value: "2-2-1",
            path: "/index/all/ringMonitor/monitor",
            perms: "dynamic:control:list",
            children: [],
          },
          {
            label: "运行分析",
            parent: "2-2",
            value: "2-2-2",
            path: "/index/all/ringMonitor/analysis",
            perms: "dynamic:analysis:list",
            children: [],
          },
          {
            label: "实时监控",
            parent: "2-2",
            value: "2-2-3",
            path: "/index/all/ringMonitor/ringMonitoring",
            perms: "dynamic:monitoring:list",
            children: [],
          },
          {
            label: "动环监控",
            parent: "2-2",
            value: "2-2-4",
            path: "/index/all/ringMonitor/ring",
            perms: "dynamic:ring:list",
            children: [],
          },
          {
            label: "视频监控",
            parent: "2-2",
            value: "2-2-5",
            path: "/index/all/ringMonitor/videoMonitor",
            perms: "dynamic:video:list",
            children: [],
          },
        ],
      },
    ],
  },
  // {
  //   label: "运行监控",
  //   value: "2",
  //   perms: [
  //     "monitor:overview:list",
  //     "monitor:monitoring:list",
  //     "monitor:condition:list",
  //     "monitor:alarm:list"
  //   ],
  //   children: [
  //     {
  //       label: "运行概况",
  //       parent: "2",
  //       value: "2-1",
  //       path: "/index/monitor/runoverview",
  //       perms: "monitor:overview:list",
  //       children: []
  //     },
  //     {
  //       label: "实时监控",
  //       parent: "2",
  //       value: "2-2",
  //       path: "/index/monitor/monitoring",
  //       perms: "monitor:monitoring:list",
  //       children: []
  //     },
  //     {
  //       label: "工况查询",
  //       parent: "2",
  //       value: "2-3",
  //       path: "/index/monitor/wcquery",
  //       perms: "monitor:condition:list",
  //       children: []
  //     },
  //     {
  //       label: "告警列表",
  //       parent: "2",
  //       value: "2-4",
  //       path: "/index/monitor/alarm",
  //       perms: "monitor:alarm:list",
  //       children: []
  //     }
  //   ]
  // },
  // {
  //   label: "动环监控",
  //   value: "3",
  //   perms: [
  //     "dynamic:control:list",
  //     "dynamic:analysis:list",
  //     "dynamic:video:list",
  //     "dynamic:monitoring:list"
  //   ],
  //   children: [
  //     {
  //       label: "运行监测",
  //       parent: "3",
  //       value: "3-1",
  //       path: "/index/ringMonitor/monitor",
  //       perms: "dynamic:control:list",
  //       children: []
  //     },
  //     {
  //       label: "运行分析",
  //       parent: "3",
  //       value: "3-2",
  //       path: "/index/ringMonitor/analysis",
  //       perms: "dynamic:analysis:list",
  //       children: []
  //     },
  //     {
  //       label: "实时监控",
  //       parent: "3",
  //       value: "3-3",
  //       path: "/index/ringMonitor/ringMonitoring",
  //       perms: "dynamic:monitoring:list",
  //       children: []
  //     },
  //     {
  //       label: "视频监控",
  //       parent: "3",
  //       value: "3-4",
  //       path: "/index/ringMonitor/videoMonitor",
  //       perms: "dynamic:video:list",
  //       children: []
  //     }
  //   ]
  // },
  {
    label: "智能运维",
    value: "3",
    perms: [
      "maintain:workOrder:list",
      "maintain:taskWorkOrder:list",
      "maintain:workorder:statistics",
      "maintain:template:query",
    ],
    children: [
      {
        label: "工单管理",
        parent: "3",
        value: "3-1",
        path: "/index/smart/repairOrder",
        perms: "maintain:workOrder:list",
        children: [],
      },
      {
        label: "计划管理",
        parent: "3",
        value: "3-2",
        path: "/index/smart/plan",
        perms: "maintain:taskWorkOrder:list",
        children: [],
      },
      {
        label: "工单统计",
        parent: "3",
        value: "3-3",
        path: "/index/smart/statistical",
        perms: "maintain:workorder:statistics",
        children: [],
      },
      {
        label: "巡视模板管理",
        parent: "3",
        value: "3-4",
        path: "/index/smart/temMan",
        perms: "maintain:template:query",
        children: [],
      },
    ],
  },
  {
    label: "设备台账",
    value: "4",
    ref: "ema",
    perms: [
      "ema:qType:list",
      "ema:eptment:list",
      "ema:room:tree",
      "ema:cd:list",
    ],
    children: [
      {
        label: "参数管理",
        parent: "4",
        value: "4-1",
        path: "/index/equipmentParameter/parameter",
        perms: "ema:qType:list",
        children: [],
      },
      {
        label: "型号管理",
        parent: "4",
        value: "4-2",
        path: "/index/equipmentParameter/marking",
        perms: "ema:eptment:list",
        children: [],
      },
      {
        label: "设备管理",
        parent: "4",
        value: "4-3",
        path: "/index/equipmentParameter/device",
        perms: "ema:room:tree",
        children: [],
      },
      {
        label: "接线图管理",
        parent: "4",
        value: "4-4",
        path: "/index/equipmentParameter/drawadd",
        perms: "ema:cd:list",
        children: [],
      },
    ],
  },
  {
    label: "统计分析",
    value: "5",
    perms: [
      "report:timeSharingElectricity:list",
      "report:load:list",
      "report:electricity:list",
      "report:run:list",
      "report:mostValueAnalysis:list",
      "report:transformerLoadRatio:list",
      "report:electricityStatistics:list",
    ],
    children: [
      {
        label: "分时电量统计",
        parent: "5",
        value: "5-1",
        path: "/index/statistical/timeElectricityTab",
        perms: "report:timeSharingElectricity:list",
        children: [],
      },
      {
        label: "负荷曲线",
        parent: "5",
        value: "5-2",
        path: "/index/statistical/load",
        perms: "report:load:list",
        children: [],
      },
      {
        label: "电量报表",
        parent: "5",
        value: "5-3",
        path: "/index/statistical/electricity",
        perms: "report:electricity:list",
        children: [],
      },
      {
        label: "运行报表",
        parent: "5",
        value: "5-4",
        path: "/index/statistical/run",
        perms: "report:run:list",
        children: [],
      },
      {
        label: "最值分析",
        parent: "5",
        value: "5-5",
        path: "/index/statistical/mostValueAnalysis",
        perms: "report:mostValueAnalysis:list",
        children: [],
      },
      {
        label: "变压器负载率",
        parent: "5",
        value: "5-6",
        path: "/index/statistical/transformerLoadRatio",
        perms: "report:transformerLoadRatio:list",
        children: [],
      },
      {
        label: "用电统计",
        parent: "5",
        value: "5-7",
        path: "/index/statistical/electricityStatistics",
        perms: "report:electricityStatistics:list",
        children: [],
      },
    ],
  },
  {
    label: "优化用电",
    value: "6",
    perms: [
      "ele:optimize:list",
      "ele:harmonic:list",
      "ele:uUnbalanced:list",
      "ele:iUnbalanced:list",
    ],
    children: [
      {
        label: "电费优化",
        parent: "6",
        value: "6-1",
        path: "/index/optimization/optimizationList",
        perms: "ele:optimize:list",
        children: [],
      },
      {
        label: "电能质量",
        parent: "6",
        value: "6-2",
        path: "",
        perms: [
          "ele:harmonic:list",
          "ele:uUnbalanced:list",
          "ele:iUnbalanced:list",
        ],
        children: [
          {
            label: "谐波曲线",
            parent: "6-2",
            value: "6-2-1",
            path: "/index/optimization/powerQuality/harmonic",
            perms: "ele:harmonic:list",
            children: [],
          },
          {
            label: "电压不平衡",
            parent: "6-2",
            value: "6-2-2",
            path: "/index/optimization/powerQuality/voltageImbalance",
            perms: "ele:uUnbalanced:list",
            children: [],
          },
          {
            label: "电流不平衡",
            parent: "6-2",
            value: "6-2-3",
            path: "/index/optimization/powerQuality/currentImbalance",
            perms: "ele:iUnbalanced:list",
            children: [],
          },
        ],
      },
    ],
  },
  {
    label: "系统管理",
    value: "7",
    perms: [
      "system:org:list",
      "system:dept:list",
      "system:role:list",
      "monitor:operlog:list",
      "system:company:list",
      "eleprices:temp:list",
      "eleprices:config:list",
      "system:plan:list",
    ],
    children: [
      {
        label: "客户管理",
        parent: "7",
        value: "7-1",
        path: "/index/system/customer",
        perms: "system:org:list",
        children: [],
      },
      {
        label: "组织结构",
        parent: "7",
        value: "7-2",
        path: `/index/system/org/10/${
          JSON.parse(sessionStorage.getItem("userInfo")).orgId
        }`,
        perms: "system:dept:list",
        children: [],
      },
      {
        label: "角色管理",
        parent: "7",
        value: "7-3",
        path: "/index/system/role",
        perms: "system:role:list",
        children: [],
      },
      {
        label: "字典管理",
        parent: "7",
        value: "7-4",
        path: "/index/system/dictionary",
        perms: "",
        children: [],
      },
      {
        label: "菜单管理",
        parent: "7",
        value: "7-5",
        path: "/index/system/menu",
        perms: "",
        children: [],
      },
      {
        label: "区域管理",
        parent: "7",
        value: "7-6",
        path: "/index/system/area",
        perms: "",
        children: [],
      },
      {
        label: "量测量管理",
        parent: "7",
        value: "7-7",
        path: "/index/system/measure",
        perms: "",
        children: [],
      },
      {
        label: "日志查询",
        parent: "7",
        value: "7-8",
        path: "/index/system/log",
        perms: "monitor:operlog:list",
        children: [],
      },
      {
        label: "配置管理",
        parent: "7",
        value: "7-9",
        path: "",
        perms: [
          "system:company:list",
          "system:plan:list",
          "eleprices:temp:list",
          "eleprices:config:list",
        ],
        children: [
          {
            label: "抄表日配置",
            parent: "7-9",
            value: "7-9-1",
            path: "/index/system/dispose",
            perms: "system:company:list",
            children: [],
          },
          {
            label: "电价模板",
            parent: "7-9",
            value: "7-9-2",
            path: "/index/system/electrovalencelist",
            perms: "eleprices:temp:list",
            children: [],
          },
          {
            label: "企业电费配置",
            parent: "7-9",
            value: "7-9-3",
            path: "/index/system/orgdispose",
            perms: "eleprices:config:list",
            children: [],
          },
        ],
      },
      {
        label: "App应用管理",
        parent: "7",
        value: "7-11",
        path: "/index/system/appMenu",
        perms: "",
        children: [],
      },
      {
        label: "版本管理",
        parent: "7",
        value: "7-10",
        path: "/index/system/version",
        perms: "",
        children: [],
      },
      {
        label: "消息配置",
        parent: "7",
        value: "7-12",
        path: "/index/system/message/config",
        perms: "*:*:*",
        children: [],
      },
    ],
  },
];
